### ISSUE TITLE
What tech did you use for your API documentation site?

### ISSUE THREAD

**Issue by kscoulter** [nationalparkservice/nps-api-samples#5]
Hi there, not really an issue with this repo, but I was hoping to learn what tech you used for https://www.nps.gov/subjects/developer/api-documentation.htm

Helping build a developer portal for another government agency, and I was curious.

Thanks! Sorry, but I didn't know where else to put this :)

**Comment by tamills** [comment]
Hi, @kscoulter 

The api-documentation.htm page was created with the Swagger Editor and Swagger UI tools (cf. https://swagger.io/tools/). 

There **_may_** also be extensions in VS Code (for example) which can generate the equivalent, but I don't have first-hand knowledge of any specific ones which I can recommend.

**Comment by kscoulter** [comment]
Thanks!
